"""add orders table

Revision ID: ea8fd490b322
Revises: ea968a5d1636
Create Date: 2026-02-19 21:20:45.296136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea8fd490b322'
down_revision: Union[str, None] = 'ea968a5d1636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("orders",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("restaurant_id",sa.Integer(),sa.ForeignKey("restaurants.id"),nullable=False),
        sa.Column("customer_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=True),
        sa.Column("table_number",sa.String(length=20), nullable=True),
        sa.Column("status",sa.Enum("pending","accepted","preparing","ready","completed","cancelled", name="orderstatus"),nullable=False,server_default="pending"),
        sa.Column("total_amount",sa.Numeric(7, 2),nullable=False),
        sa.Column("tax_amount",sa.Numeric(7, 2),nullable=False,server_default="0"),
        sa.Column("notes",sa.String(length=500),nullable=True),
        sa.Column("created_by_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=True),
        sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)
    )
    # Optional indexes
    op.create_index("ix_orders_id", "orders", ["id"])
    op.create_index("ix_orders_status", "orders", ["status"])
    op.create_index("ix_orders_restaurant", "orders", ["restaurant_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_restaurant", table_name="orders")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_id", table_name="orders")
    op.drop_table("orders")
    op.execute("DROP TYPE IF EXISTS orderstatus")
    # ### end Alembic commands ###
