"""Fix menu category unique constraint and enforce partial uniqueness

Revision ID: e6341ef68be7
Revises: 76db1aa9fa96
Create Date: 2026-01-11 22:50:24.039945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6341ef68be7'
down_revision: Union[str, None] = '76db1aa9fa96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE menu_categories
        DROP CONSTRAINT IF EXISTS uq_menu_category_restaurant_name
        """
    )

    # 2️⃣ Drop partial index if it already exists (VERY IMPORTANT)
    op.execute(
        """
        DROP INDEX IF EXISTS uq_menu_categories_restaurant_name_non_global
        """
    )

    # 3️⃣ Re-create correct partial unique index
    op.create_index(
        "uq_menu_categories_restaurant_name_non_global",
        "menu_categories",
        ["restaurant_id", "name"],
        unique=True,
        postgresql_where=sa.text("is_global = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX IF EXISTS uq_menu_categories_restaurant_name_non_global
        """
    )

    # Restore old global unique constraint
    op.create_unique_constraint(
        "uq_menu_category_restaurant_name",
        "menu_categories",
        ["restaurant_id", "name"],
    )   
    # ### end Alembic commands ###
