"""add order_items table

Revision ID: 4cca289a8fcf
Revises: ea8fd490b322
Create Date: 2026-02-19 21:30:04.267183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cca289a8fcf'
down_revision: Union[str, None] = 'ea8fd490b322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("order_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("order_id",sa.Integer(),sa.ForeignKey("orders.id", ondelete="CASCADE"),nullable=False),
        sa.Column("menu_item_id",sa.Integer(),sa.ForeignKey("menu_items.id"),nullable=False),
        sa.Column("variant_id",sa.Integer(),sa.ForeignKey("menu_item_variants.id"),nullable=True),
        sa.Column("quantity",sa.Integer(),nullable=False),
        # Snapshot price at order time
        sa.Column("unit_price",sa.Numeric(10, 2),nullable=False),
        sa.Column("special_instructions",sa.String(length=500),nullable=True),
        sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),
        )

    # Indexes for performance
    op.create_index("ix_order_items_id", "order_items", ["id"])
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"])
    op.create_index("ix_order_items_menu_item", "order_items", ["menu_item_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_order_items_menu_item", table_name="order_items")
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    op.drop_index("ix_order_items_id", table_name="order_items")
    op.drop_table("order_items")
    # ### end Alembic commands ###
